import utils.convection_diffusion_equation_solution.kir as kir
import utils.convection_diffusion_equation_solution.beam_warming as beam
import utils.environment_properties_analyzers.visual_analyzer as va